// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuribleDotnet_back.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241022071813_AddUsers")]
    partial class AddUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aurible.Models.Book", b =>
                {
                    b.Property<int>("idBook")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idBook"));

                    b.Property<string>("audioPath")
                        .HasColumnType("text");

                    b.Property<string>("author")
                        .HasColumnType("text");

                    b.Property<string>("coverURL")
                        .HasColumnType("text");

                    b.Property<int?>("maxPage")
                        .HasColumnType("integer");

                    b.Property<string>("resume")
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.HasKey("idBook");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Aurible.Models.Chapter", b =>
                {
                    b.Property<int>("idChapter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idChapter"));

                    b.Property<string>("chapterTitle")
                        .HasColumnType("text");

                    b.Property<int>("idBook_FK")
                        .HasColumnType("integer");

                    b.Property<int>("page")
                        .HasColumnType("integer");

                    b.Property<TimeSpan[]>("timecode")
                        .HasColumnType("interval[]");

                    b.HasKey("idChapter");

                    b.HasIndex("idBook_FK");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("Aurible.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUser"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdMicrosoft")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("IdUser");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Aurible.Models.Chapter", b =>
                {
                    b.HasOne("Aurible.Models.Book", "Book")
                        .WithMany("Chapters")
                        .HasForeignKey("idBook_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Aurible.Models.Book", b =>
                {
                    b.Navigation("Chapters");
                });
#pragma warning restore 612, 618
        }
    }
}
