// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuribleDotnet_back.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aurible.Models.Book", b =>
                {
                    b.Property<int>("idBook")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idBook"));

                    b.Property<string>("audioPath")
                        .HasColumnType("text");

                    b.Property<string>("author")
                        .HasColumnType("text");

                    b.Property<string>("coverURL")
                        .HasColumnType("text");

                    b.Property<int?>("maxPage")
                        .HasColumnType("integer");

                    b.Property<string>("resume")
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.HasKey("idBook");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("Aurible.Models.Chapter", b =>
                {
                    b.Property<int>("idChapter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idChapter"));

                    b.Property<int?>("BookidBook")
                        .HasColumnType("integer");

                    b.Property<string>("chapterTitle")
                        .HasColumnType("text");

                    b.Property<int>("page")
                        .HasColumnType("integer");

                    b.Property<TimeSpan[]>("timecode")
                        .HasColumnType("interval[]");

                    b.HasKey("idChapter");

                    b.HasIndex("BookidBook");

                    b.ToTable("Chapter");
                });

            modelBuilder.Entity("Aurible.Models.Chapter", b =>
                {
                    b.HasOne("Aurible.Models.Book", "Book")
                        .WithMany("Chapters")
                        .HasForeignKey("BookidBook")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Aurible.Models.Book", b =>
                {
                    b.Navigation("Chapters");
                });
#pragma warning restore 612, 618
        }
    }
}
